export const NotesButton: React.FC = () => {
  return (
    <button type="button" className="btn btn-square">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 64 64"
        fill="none"
      >
        <rect
          x="12"
          y="8"
          width="40"
          height="48"
          rx="4"
          ry="4"
          stroke="currentColor"
          stroke-width="2"
        />

        <line
          x1="20"
          y1="8"
          x2="20"
          y2="4"
          stroke="currentColor"
          stroke-width="2"
        />
        <line
          x1="28"
          y1="8"
          x2="28"
          y2="4"
          stroke="currentColor"
          stroke-width="2"
        />
        <line
          x1="36"
          y1="8"
          x2="36"
          y2="4"
          stroke="currentColor"
          stroke-width="2"
        />
        <line
          x1="44"
          y1="8"
          x2="44"
          y2="4"
          stroke="currentColor"
          stroke-width="2"
        />

        <line
          x1="16"
          y1="20"
          x2="48"
          y2="20"
          stroke="currentColor"
          stroke-width="1.5"
          opacity="0.6"
        />
        <line
          x1="16"
          y1="28"
          x2="48"
          y2="28"
          stroke="currentColor"
          stroke-width="1.5"
          opacity="0.6"
        />
        <line
          x1="16"
          y1="36"
          x2="48"
          y2="36"
          stroke="currentColor"
          stroke-width="1.5"
          opacity="0.6"
        />
        <line
          x1="16"
          y1="44"
          x2="48"
          y2="44"
          stroke="currentColor"
          stroke-width="1.5"
          opacity="0.6"
        />
        <line
          x1="16"
          y1="52"
          x2="48"
          y2="52"
          stroke="currentColor"
          stroke-width="1.5"
          opacity="0.6"
        />
      </svg>
    </button>
  );
};
